# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b371820d04fd3eac974aa90aa4404b0b0c3524777af272a6a6cd29ac1453c881737aa21b6e41c3d093f279b174fad74e7a760e045b90bd448ebb49c1f52478b

test:
  secret_key_base: 65c5ffca43391eb7330a6641137a037d6f5f8feba0e3cd84bb577a33b212a7d32077812c82892c959e83f9960dccf75d53b4f587c31e9b04113017763dad0091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
